### ISSUE TITLE
Game crashes on startup if overlay application is running

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#41] opened 2020-10-11 13:53 UTC
Game crashes on startup if overlay application is running.
MSI Afterburner is confirmed to crash. Possibly happens with Steam Overlay and such applications too.
It doesn't crash without d3d8.dll, possibly some hook conflict.
It also doesn't crash if overlay is launched after the game.

A possibly related case, I observed it periodically crashes on startup if Visual Studio 2019 is running.

**Comment by Vadru93** [comment] 2020-10-13 10:47
I’m not sure this is fixable since I know quite a few AAA games that has this issue. And the visual studio is weird, since I always have visual studio on. Does it only happen in fullscreen?

**Comment by Vadru93** [comment] 2020-10-27 12:47
I don't seem to be able to reproduce this behaviour, either it's something else crashing you, or this is only happening in windows 7. But I didn't have this issue in windows 7 either so I'm closing this for now.

**Closed** 2020-10-27 12:47 UTC
Labels: DLL, On hold, bug, game crash

**Comment by DCxDemo** [comment] 2020-10-27 15:14
Confirmed to work with the latest dll on win7.
