### ISSUE TITLE
Crash issue when pressing buttons

### ISSUE THREAD

**Issue by Vadru93** [Vadru93/LevelMod#14] opened 2020-09-13 17:43 UTC
If keep spamming buttons while game is loading it, or a level is loading it sometimes crashes

**Comment by DCxDemo** [comment] 2021-02-08 13:24
this seems to be fixed now?

**Comment by Vadru93** [comment] 2022-12-21 20:19
This is tested to be fixed now.

**Comment by DCxDemo** [comment] 2023-04-16 10:19
Can't reproduce in current build, closing.

**Closed by DCxDemo** 2023-04-16 10:19 UTC
Labels: bug, game crash
